package agents;

/**
 * Created by ruben on 10/11/2016.
 */
public enum State {
    CONNECTING,CONNECTINGSENT,WAITING,SLEEP,WAKE,REGISTER,STARTING,ALLCONNECTED,GAMESTARTING,ALIVE,
    WEREWOLVES_VOTING, DAY_VOTING, WAITING_VOTES,WAITING_VOTES_WEREWOLVES,GAMEDONE,DEAD;
}
