package agents;

/**
 * Created by ruben on 10/11/2016.
 */
public enum State {
    CONNECTING,CONNECTINGSENT,WAITING,SLEEP,WAKE,REGISTER,STARTING,ALLCONNECTED,GAMEON,
    WEREWOLVES_VOTING, DAY_VOTING;
}
